using System.Text;
using CrtGeometry.Core;
using CrtGeometry.Data;
using Microsoft.Data.Sqlite;

namespace CrtGeometry.Tests;

public sealed class FirmwareDatabaseGeneratorTests : IDisposable
{
    private readonly string _directory = Path.Combine(Path.GetTempPath(), $"crtgeometry-firmware-{Guid.NewGuid():N}");
    private readonly string _databasePath;
    private readonly string _connectionString;

    public FirmwareDatabaseGeneratorTests()
    {
        Directory.CreateDirectory(_directory);
        _databasePath = Path.Combine(_directory, "profiles.db");
        _connectionString = new SqliteConnectionStringBuilder { DataSource = _databasePath }.ToString();
        new DatabaseInitializer(_connectionString).Initialize();
    }

    [Fact]
    public void EmptyDatabaseEmitsCompleteInvalidDirectIndexTable()
    {
        var result = new FirmwareDatabaseGenerator(_connectionString).Preview();

        Assert.Equal(0, result.Statistics.ProfileCount);
        Assert.Equal(0, result.Statistics.HighestProfileId);
        Assert.Equal(1280, result.Statistics.ProfileTableBytes);
        Assert.Equal(32, result.Statistics.ValidityBytes);
        Assert.Equal(1366, result.Statistics.TotalBytes);
        Assert.Equal(256, result.Content.Split('\n').Count(line => line.TrimStart().StartsWith("{ ")));
        Assert.Contains("{ 0, 0, 0, 0, 0 }, // 0\n", result.Content);
        Assert.Contains("0x00, 0x00, 0x00, 0x00", result.Content);
    }

    [Fact]
    public void SparseProfilesRemainAtTheirIdsAndSetValidityBits()
    {
        var first = Profile(17, 33, 11, 30, 13, 63);
        var zero = Profile(42, 0, 0, 0, 0, 0);
        var last = Profile(255, 1, 2, 3, 4, 5);

        var result = FirmwareDatabaseGenerator.Generate([last, zero, first]);

        Assert.Equal(3, result.Statistics.ProfileCount);
        Assert.Equal(255, result.Statistics.HighestProfileId);
        Assert.Contains("{ 33, 11, 30, 13, 63 }, // 17", result.Content);
        Assert.Contains("{ 0, 0, 0, 0, 0 }, // 42", result.Content);
        Assert.Contains("{ 1, 2, 3, 4, 5 } // 255", result.Content);
        var bitmap = Bitmap(result.Content);
        Assert.Equal(0x02, bitmap[2]); // ID 17
        Assert.Equal(0x04, bitmap[5]); // ID 42 exists despite all-zero geometry
        Assert.Equal(0x80, bitmap[31]); // ID 255
        Assert.Equal(0, bitmap[0]); // ID 0 is always invalid
    }

    [Fact]
    public void GenerationIsDeterministicAndHasConservativeAvrHeader()
    {
        var profiles = new[] { Profile(9, 5, 4, 3, 2, 1), Profile(2, 1, 2, 3, 4, 5) };
        var forward = FirmwareDatabaseGenerator.Generate(profiles).Content;
        var reverse = FirmwareDatabaseGenerator.Generate(profiles.Reverse()).Content;

        Assert.Equal(forward, reverse);
        Assert.StartsWith("// AUTO-GENERATED BY CRT GEOMETRY\n// DO NOT EDIT MANUALLY\n", forward);
        Assert.Contains("const uint16_t GENERATED_PROFILE_COUNT = 2;", forward);
        Assert.Contains("const uint8_t GENERATED_MAX_PROFILE_ID = 9;", forward);
        Assert.Contains("PROGMEM", forward);
        Assert.DoesNotContain("timestamp", forward, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("namespace", forward);
        Assert.DoesNotContain("std::", forward);
        Assert.DoesNotContain('\r', forward);
    }

    [Fact]
    public void DuplicateIdsAreRejected()
    {
        var duplicate = Profile(3, 1, 2, 3, 4, 5);
        var exception = Assert.Throws<InvalidDataException>(() =>
            FirmwareDatabaseGenerator.Generate([duplicate, duplicate]));
        Assert.Contains("Duplicate profile ID 3", exception.Message);
    }

    [Fact]
    public void WriteUsesUtf8WithoutBomAndExactFileName()
    {
        new GeometryProfileRepository(_connectionString).Save(Profile(1, 33, 11, 30, 13, 63));
        var output = Path.Combine(_directory, "firmware");

        var stats = new FirmwareDatabaseGenerator(_connectionString).Write(output);
        var bytes = File.ReadAllBytes(Path.Combine(output, FirmwareDatabaseGenerator.OutputFileName));

        Assert.Equal(1, stats.ProfileCount);
        Assert.False(bytes.AsSpan().StartsWith(Encoding.UTF8.Preamble));
        Assert.Equal(FirmwareDatabaseGenerator.Generate([Profile(1, 33, 11, 30, 13, 63)]).Content,
            Encoding.UTF8.GetString(bytes));
        Assert.Single(Directory.GetFiles(output));
    }

    [Fact]
    public void FailedDatabaseValidationDoesNotOverwriteExistingHeader()
    {
        var output = Path.Combine(_directory, "firmware");
        Directory.CreateDirectory(output);
        var target = Path.Combine(output, FirmwareDatabaseGenerator.OutputFileName);
        File.WriteAllText(target, "known good");
        using (var connection = SqliteConnectionFactory.Open(_connectionString))
        using (var command = connection.CreateCommand())
        {
            command.CommandText = "PRAGMA ignore_check_constraints=ON; INSERT INTO GeometryProfiles VALUES(1,64,0,0,0,0,NULL);";
            command.ExecuteNonQuery();
        }

        Assert.Throws<ArgumentOutOfRangeException>(() => new FirmwareDatabaseGenerator(_connectionString).Write(output));
        Assert.Equal("known good", File.ReadAllText(target));
        Assert.Single(Directory.GetFiles(output));
    }

    [Fact]
    public void NamesNormalizePackContinuouslyAndRoundTrip()
    {
        Assert.Equal("R-TYPE LEO'S + 2!", FirmwareDatabaseGenerator.NormalizeDisplayName("  R-Type\tLéo’s + 2! ☃ "));
        var result = FirmwareDatabaseGenerator.Generate([Profile(1, 1, 2, 3, 4, 5)],
            [new("rtype", "R-Type", 1), new("long", "A Recognizable Game Title Longer Than Twenty", 1)]);

        Assert.Equal(0U, result.Games[0].NameBitOffset);
        Assert.True(result.Games.Single(g => g.RomName == "long").DisplayName.Length > 20);
        for (var i = 0; i < result.Games.Count; i++)
        {
            var end = i + 1 < result.Games.Count ? result.Games[i + 1].NameBitOffset : (uint)result.Statistics.TotalNameBits;
            Assert.Equal(result.Games[i].DisplayName,
                FirmwareDatabaseGenerator.DecodeName(result.PackedNames, result.Games[i].NameBitOffset, end - result.Games[i].NameBitOffset));
        }
        Assert.Equal(result.Games[0].DisplayName.Length * 6U, result.Games[1].NameBitOffset);
    }

    [Fact]
    public void CollisionsAreVisibleAndOrderingIsDeterministic()
    {
        var games = new[] { new FirmwareGame("dkongb", "Donkey Kong", 7), new("dkong", "Donkey Kong", 7) };
        var result = FirmwareDatabaseGenerator.Generate([Profile(7, 1, 1, 1, 1, 1)], games.Reverse());
        Assert.Equal(new[] { "DONKEY KONG [DKONG]", "DONKEY KONG [DKONGB]" }, result.Games.Select(g => g.DisplayName));
        Assert.Equal(result.Content, FirmwareDatabaseGenerator.Generate([Profile(7, 1, 1, 1, 1, 1)], games).Content);
        Assert.All(result.Games, g => Assert.Equal(7, g.ProfileId));
    }

    [Theory]
    [InlineData(700)]
    [InlineData(1500)]
    public void SyntheticDatabasesUseChecked32BitContinuousOffsets(int count)
    {
        var games = Enumerable.Range(0, count).Select(i => new FirmwareGame($"rom{i:D4}", $"Game {i:D4} Long Name", 255));
        var result = FirmwareDatabaseGenerator.Generate([Profile(255, 1, 2, 3, 4, 5)], games);
        Assert.Equal(count, result.Statistics.GameCount);
        Assert.Equal(count * 4, result.Statistics.OffsetBytes);
        Assert.Equal(result.Statistics.TotalNameBits, result.Games.Sum(g => g.DisplayName.Length) * 6);
        Assert.True(result.Games[^1].NameBitOffset > ushort.MaxValue || count == 700);
    }

    [Fact]
    public void InvalidMappingsAndOffsetOverflowAreRejected()
    {
        Assert.Throws<InvalidDataException>(() => FirmwareDatabaseGenerator.Generate([Profile(1, 1, 1, 1, 1, 1)], [new("bad", "Bad", 2)]));
        Assert.Throws<InvalidDataException>(() => FirmwareDatabaseGenerator.ValidateTotalNameBits((long)uint.MaxValue + 1));
    }

    [Fact]
    public void PreviewEmitsOnlyAssignedPresentIncludedGames()
    {
        new GeometryProfileRepository(_connectionString).Save(Profile(1, 1, 2, 3, 4, 5));
        using (var connection = SqliteConnectionFactory.Open(_connectionString))
        using (var command = connection.CreateCommand())
        {
            command.CommandText = """
                INSERT INTO MameImports(Id,ImportedAtUtc,DurationMilliseconds,TotalMachines,IncludedMachines,MachinesWithDisplays)
                VALUES(1,'x',0,5,3,0);
                INSERT INTO MameMachines(RomName,Description,Runnable,IsBios,IsDevice,IsMechanical,ExclusionReasons,IsIncluded,LastImportId,IsPresent) VALUES
                  ('good','Good Game',1,0,0,0,0,1,1,1),
                  ('goodclone','Good Game Clone',1,0,0,0,0,1,1,1),
                  ('unassigned','No Assignment',1,0,0,0,0,1,1,1),
                  ('absent','Absent Game',1,0,0,0,0,1,1,0),
                  ('excluded','Excluded Game',1,0,0,0,8,0,1,1);
                INSERT INTO GameProfileAssignments(RomName,ProfileId,AssignmentType,UpdatedAtUtc) VALUES
                  ('good',1,2,'x'),('goodclone',1,2,'x'),('absent',1,2,'x'),('excluded',1,2,'x');
                UPDATE MameMachines SET CloneOf='good' WHERE RomName='goodclone';
                """;
            command.ExecuteNonQuery();
        }
        var result = new FirmwareDatabaseGenerator(_connectionString).Preview();
        Assert.Single(result.Games);
        Assert.Equal("good", result.Games[0].RomName);
        Assert.Equal(1, result.Games[0].ProfileId);
        Assert.DoesNotContain(result.Games, game => game.RomName == "goodclone");
    }

    [Fact]
    public void JumpTableHasHashLettersAndEmptySentinels()
    {
        var result = FirmwareDatabaseGenerator.Generate([Profile(1, 1, 1, 1, 1, 1)],
            [new("num", "1942", 1), new("alpha", "Alpha", 1), new("middle", "Mario", 1), new("zed", "Zaxxon", 1)]);
        Assert.Equal(0, result.AlphabetJumps[0]);
        Assert.Equal(1, result.AlphabetJumps[1]);
        Assert.Equal(result.Statistics.GameCount, result.AlphabetJumps[2]);
        Assert.Equal(2, result.AlphabetJumps['M' - 'A' + 1]);
        Assert.Equal(3, result.AlphabetJumps[26]);
    }

    private static GeometryProfile Profile(int id, int hsh, int vsl, int vam, int vsc, int vsh) =>
        new(id) { HSH = hsh, VSL = vsl, VAM = vam, VSC = vsc, VSH = vsh };

    private static byte[] Bitmap(string content)
    {
        var marker = "const uint8_t GENERATED_PROFILE_VALIDITY[32] PROGMEM =";
        var section = content[(content.IndexOf(marker, StringComparison.Ordinal) + marker.Length)..];
        return System.Text.RegularExpressions.Regex.Matches(section, "0x([0-9A-F]{2})")
            .Cast<System.Text.RegularExpressions.Match>()
            .Select(match => Convert.ToByte(match.Groups[1].Value, 16)).ToArray();
    }

    public void Dispose()
    {
        SqliteConnection.ClearAllPools();
        Directory.Delete(_directory, true);
    }
}
