using System.Text;
using CrtGeometry.Core;
using CrtGeometry.Data;
using Microsoft.Data.Sqlite;

namespace CrtGeometry.Tests;

public sealed class FirmwareDatabaseGeneratorTests : IDisposable
{
    private readonly string _directory = Path.Combine(Path.GetTempPath(), $"crtgeometry-firmware-{Guid.NewGuid():N}");
    private readonly string _databasePath;
    private readonly string _connectionString;

    public FirmwareDatabaseGeneratorTests()
    {
        Directory.CreateDirectory(_directory);
        _databasePath = Path.Combine(_directory, "profiles.db");
        _connectionString = new SqliteConnectionStringBuilder { DataSource = _databasePath }.ToString();
        new DatabaseInitializer(_connectionString).Initialize();
    }

    [Fact]
    public void EmptyDatabaseEmitsCompleteInvalidDirectIndexTable()
    {
        var result = new FirmwareDatabaseGenerator(_connectionString).Preview();

        Assert.Equal(0, result.Statistics.ProfileCount);
        Assert.Equal(0, result.Statistics.HighestProfileId);
        Assert.Equal(1280, result.Statistics.ProfileTableBytes);
        Assert.Equal(32, result.Statistics.ValidityBytes);
        Assert.Equal(1312, result.Statistics.TotalBytes);
        Assert.Equal(256, result.Content.Split('\n').Count(line => line.TrimStart().StartsWith("{ ")));
        Assert.Contains("{ 0, 0, 0, 0, 0 }, // 0\n", result.Content);
        Assert.Contains("0x00, 0x00, 0x00, 0x00", result.Content);
    }

    [Fact]
    public void SparseProfilesRemainAtTheirIdsAndSetValidityBits()
    {
        var first = Profile(17, 33, 11, 30, 13, 63);
        var zero = Profile(42, 0, 0, 0, 0, 0);
        var last = Profile(255, 1, 2, 3, 4, 5);

        var result = FirmwareDatabaseGenerator.Generate([last, zero, first]);

        Assert.Equal(3, result.Statistics.ProfileCount);
        Assert.Equal(255, result.Statistics.HighestProfileId);
        Assert.Contains("{ 33, 11, 30, 13, 63 }, // 17", result.Content);
        Assert.Contains("{ 0, 0, 0, 0, 0 }, // 42", result.Content);
        Assert.Contains("{ 1, 2, 3, 4, 5 } // 255", result.Content);
        var bitmap = Bitmap(result.Content);
        Assert.Equal(0x02, bitmap[2]); // ID 17
        Assert.Equal(0x04, bitmap[5]); // ID 42 exists despite all-zero geometry
        Assert.Equal(0x80, bitmap[31]); // ID 255
        Assert.Equal(0, bitmap[0]); // ID 0 is always invalid
    }

    [Fact]
    public void GenerationIsDeterministicAndHasConservativeAvrHeader()
    {
        var profiles = new[] { Profile(9, 5, 4, 3, 2, 1), Profile(2, 1, 2, 3, 4, 5) };
        var forward = FirmwareDatabaseGenerator.Generate(profiles).Content;
        var reverse = FirmwareDatabaseGenerator.Generate(profiles.Reverse()).Content;

        Assert.Equal(forward, reverse);
        Assert.StartsWith("// AUTO-GENERATED BY CRT GEOMETRY\n// DO NOT EDIT MANUALLY\n", forward);
        Assert.Contains("const uint16_t GENERATED_PROFILE_COUNT = 2;", forward);
        Assert.Contains("const uint8_t GENERATED_MAX_PROFILE_ID = 9;", forward);
        Assert.Contains("PROGMEM", forward);
        Assert.DoesNotContain("timestamp", forward, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("namespace", forward);
        Assert.DoesNotContain("std::", forward);
        Assert.DoesNotContain('\r', forward);
    }

    [Fact]
    public void DuplicateIdsAreRejected()
    {
        var duplicate = Profile(3, 1, 2, 3, 4, 5);
        var exception = Assert.Throws<InvalidDataException>(() =>
            FirmwareDatabaseGenerator.Generate([duplicate, duplicate]));
        Assert.Contains("Duplicate profile ID 3", exception.Message);
    }

    [Fact]
    public void WriteUsesUtf8WithoutBomAndExactFileName()
    {
        new GeometryProfileRepository(_connectionString).Save(Profile(1, 33, 11, 30, 13, 63));
        var output = Path.Combine(_directory, "firmware");

        var stats = new FirmwareDatabaseGenerator(_connectionString).Write(output);
        var bytes = File.ReadAllBytes(Path.Combine(output, FirmwareDatabaseGenerator.OutputFileName));

        Assert.Equal(1, stats.ProfileCount);
        Assert.False(bytes.AsSpan().StartsWith(Encoding.UTF8.Preamble));
        Assert.Equal(FirmwareDatabaseGenerator.Generate([Profile(1, 33, 11, 30, 13, 63)]).Content,
            Encoding.UTF8.GetString(bytes));
        Assert.Single(Directory.GetFiles(output));
    }

    [Fact]
    public void FailedDatabaseValidationDoesNotOverwriteExistingHeader()
    {
        var output = Path.Combine(_directory, "firmware");
        Directory.CreateDirectory(output);
        var target = Path.Combine(output, FirmwareDatabaseGenerator.OutputFileName);
        File.WriteAllText(target, "known good");
        using (var connection = SqliteConnectionFactory.Open(_connectionString))
        using (var command = connection.CreateCommand())
        {
            command.CommandText = "PRAGMA ignore_check_constraints=ON; INSERT INTO GeometryProfiles VALUES(1,64,0,0,0,0,NULL);";
            command.ExecuteNonQuery();
        }

        Assert.Throws<ArgumentOutOfRangeException>(() => new FirmwareDatabaseGenerator(_connectionString).Write(output));
        Assert.Equal("known good", File.ReadAllText(target));
        Assert.Single(Directory.GetFiles(output));
    }

    private static GeometryProfile Profile(int id, int hsh, int vsl, int vam, int vsc, int vsh) =>
        new(id) { HSH = hsh, VSL = vsl, VAM = vam, VSC = vsc, VSH = vsh };

    private static byte[] Bitmap(string content)
    {
        var marker = "const uint8_t GENERATED_PROFILE_VALIDITY[32] PROGMEM =";
        var section = content[(content.IndexOf(marker, StringComparison.Ordinal) + marker.Length)..];
        return System.Text.RegularExpressions.Regex.Matches(section, "0x([0-9A-F]{2})")
            .Cast<System.Text.RegularExpressions.Match>()
            .Select(match => Convert.ToByte(match.Groups[1].Value, 16)).ToArray();
    }

    public void Dispose()
    {
        SqliteConnection.ClearAllPools();
        Directory.Delete(_directory, true);
    }
}
