using System.Text;
using CrtGeometry.Core;

namespace CrtGeometry.Data;

public sealed record FirmwareDatabaseStatistics(
    int ProfileCount,
    int HighestProfileId,
    int ProfileTableBytes,
    int ValidityBytes)
{
    public int TotalBytes => ProfileTableBytes + ValidityBytes;
}

public sealed record FirmwareDatabaseGeneration(string Content, FirmwareDatabaseStatistics Statistics);

/// <summary>Generates the AVR geometry-profile include from authoritative SQLite state.</summary>
public sealed class FirmwareDatabaseGenerator(string connectionString)
{
    public const string OutputFileName = "GeneratedDatabase.h";
    public const int ProfileSlotCount = 256;
    public const int GeometryBytesPerProfile = 5;
    public const int ValidityByteCount = ProfileSlotCount / 8;

    public FirmwareDatabaseGeneration Preview() =>
        Generate(new GeometryProfileRepository(connectionString).GetAll());

    public FirmwareDatabaseStatistics Write(string firmwareDirectory)
    {
        var generation = Preview(); // Validate before touching the destination.
        if (string.IsNullOrWhiteSpace(firmwareDirectory))
            throw new ArgumentException("Select a firmware directory.", nameof(firmwareDirectory));

        Directory.CreateDirectory(firmwareDirectory);
        var target = Path.Combine(firmwareDirectory, OutputFileName);
        var temporary = Path.Combine(firmwareDirectory, $".{OutputFileName}.{Guid.NewGuid():N}.tmp");
        try
        {
            File.WriteAllText(temporary, generation.Content, new UTF8Encoding(false));
            if (File.Exists(target))
                File.Replace(temporary, target, null);
            else
                File.Move(temporary, target);
        }
        finally
        {
            if (File.Exists(temporary)) File.Delete(temporary);
        }
        return generation.Statistics;
    }

    public static FirmwareDatabaseGeneration Generate(IEnumerable<GeometryProfile> source)
    {
        ArgumentNullException.ThrowIfNull(source);
        var profiles = source.OrderBy(profile => profile.Id).ToArray();
        var ids = new HashSet<int>();
        foreach (var profile in profiles)
        {
            if (profile.Id is < 1 or > 255)
                throw new InvalidDataException($"Profile ID {profile.Id} must be between 1 and 255.");
            if (!ids.Add(profile.Id))
                throw new InvalidDataException($"Duplicate profile ID {profile.Id}.");
            ValidateGeometry(profile.HSH, nameof(profile.HSH), profile.Id);
            ValidateGeometry(profile.VSL, nameof(profile.VSL), profile.Id);
            ValidateGeometry(profile.VAM, nameof(profile.VAM), profile.Id);
            ValidateGeometry(profile.VSC, nameof(profile.VSC), profile.Id);
            ValidateGeometry(profile.VSH, nameof(profile.VSH), profile.Id);
        }

        var byId = profiles.ToDictionary(profile => profile.Id);
        var bitmap = new byte[ValidityByteCount];
        foreach (var profile in profiles) bitmap[profile.Id >> 3] |= (byte)(1 << (profile.Id & 7));
        var highestId = profiles.Length == 0 ? 0 : profiles[^1].Id;
        var stats = new FirmwareDatabaseStatistics(profiles.Length, highestId,
            ProfileSlotCount * GeometryBytesPerProfile, ValidityByteCount);

        var text = new StringBuilder(13_000);
        text.Append("// AUTO-GENERATED BY CRT GEOMETRY\n")
            .Append("// DO NOT EDIT MANUALLY\n\n")
            .Append("#ifndef CRT_GEOMETRY_GENERATED_DATABASE_H\n")
            .Append("#define CRT_GEOMETRY_GENERATED_DATABASE_H\n\n")
            .Append("#include <Arduino.h>\n")
            .Append("#include <avr/pgmspace.h>\n\n")
            .Append("struct GeneratedGeometryProfile\n{\n")
            .Append("    uint8_t hsh;\n    uint8_t vsl;\n    uint8_t vam;\n    uint8_t vsc;\n    uint8_t vsh;\n};\n\n")
            .Append("const uint16_t GENERATED_PROFILE_COUNT = ").Append(profiles.Length).Append(";\n")
            .Append("const uint8_t GENERATED_MAX_PROFILE_ID = ").Append(highestId).Append(";\n")
            .Append("const uint8_t GENERATED_PROFILE_VALIDITY_BYTES = 32;\n\n")
            .Append("const GeneratedGeometryProfile GENERATED_PROFILES[256] PROGMEM =\n{\n");
        for (var id = 0; id < ProfileSlotCount; id++)
        {
            var values = byId.TryGetValue(id, out var profile)
                ? $"{profile.HSH}, {profile.VSL}, {profile.VAM}, {profile.VSC}, {profile.VSH}"
                : "0, 0, 0, 0, 0";
            text.Append("    { ").Append(values).Append(" }");
            if (id != 255) text.Append(',');
            text.Append(" // ").Append(id).Append('\n');
        }
        text.Append("};\n\nconst uint8_t GENERATED_PROFILE_VALIDITY[32] PROGMEM =\n{\n    ");
        for (var index = 0; index < bitmap.Length; index++)
        {
            if (index > 0) text.Append(index % 8 == 0 ? ",\n    " : ", ");
            text.Append("0x").Append(bitmap[index].ToString("X2"));
        }
        text.Append("\n};\n\n#endif\n");
        return new FirmwareDatabaseGeneration(text.ToString(), stats);
    }

    private static void ValidateGeometry(int value, string field, int id)
    {
        if (value is < 0 or > 63)
            throw new InvalidDataException($"Profile {id} {field} value {value} must be between 0 and 63.");
    }
}
